name: browser-cookies
ui: jasmine
browsers:
  - name: android
    version: oldest
  - name: android
    version: 4.4
  - name: android
    version: 5.0
  - name: android
    version: latest
  - name: iphone
    version: oldest
  - name: iphone
    version: 6
  - name: iphone
    version: 7
  - name: iphone
    version: 8
  - name: iphone
    version: 9
  - name: iphone
    version: latest
  - name: chrome
    version: oldest
  - name: chrome
    version: 30
  - name: chrome
    version: 40
  - name: chrome
    version: latest
  - name: firefox
    version: oldest
  - name: firefox
    version: 10
  - name: firefox
    version: 20
  - name: firefox
    version: 30
  - name: firefox
    version: 40
  - name: firefox
    version: latest
  - name: internet explorer
    version: oldest..latest
  - name: microsoftedge
    version: oldest..latest
  - name: opera
    version: oldest..latest
  - name: safari
    version: oldest..latest
scripts:
  - "dist/browser-cookies.test.js"
